const books = [
  {
    id: 1,
    title: "The Noble Qur'an",
    author: "Translated by Dr. Muhsin Khan & Dr. Taqi-ud-Din al-Hilali",
    genre: "Religious",
    price: 499,
    available: true,
  },
  {
    id: 2,
    title: "Riyadh as-Salihin",
    author: "Imam Nawawi",
    genre: "Hadith",
    price: 650,
    available: true,
  },
  {
    id: 3,
    title: "Sahih al-Bukhari",
    author: "Imam al-Bukhari",
    genre: "Hadith",
    price: 1200,
    available: false,
  },
  {
    id: 4,
    title: "Fortress of the Muslim (Hisn al-Muslim)",
    author: "Said bin Ali bin Wahf al-Qahtani",
    genre: "Dua & Supplications",
    price: 200,
    available: true,
  },
  {
    id: 5,
    title: "Ar-Raheeq al-Makhtum (The Sealed Nectar)",
    author: "Safi-ur-Rahman al-Mubarakpuri",
    genre: "Seerah",
    price: 550,
    available: true,
  },
  {
    id: 6,
    title: "Fiqh-us-Sunnah",
    author: "As-Sayyid Sabiq",
    genre: "Fiqh",
    price: 700,
    available: true,
  },
  {
    id: 7,
    title: "Stories of the Prophets",
    author: "Ibn Kathir",
    genre: "History",
    price: 400,
    available: true,
  },
  {
    id: 8,
    title: "40 Hadith of Imam Nawawi",
    author: "Imam Nawawi",
    genre: "Hadith",
    price: 250,
    available: true,
  },
  {
    id: 9,
    title: "Tafsir Ibn Kathir (Abridged)",
    author: "Ibn Kathir",
    genre: "Tafsir",
    price: 1500,
    available: false,
  },
  {
    id: 10,
    title: "Purification of the Soul",
    author: "Compiled from works of Ibn Rajab, Ibn al-Qayyim, and Imam al-Ghazali",
    genre: "Spirituality",
    price: 350,
    available: true,
  },
];

module.exports = books;
